"""
Outbound port interfaces — what the application needs from infrastructure.
These are the contracts that infrastructure adapters must implement.
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from ..domain.models import Signal, Order, Position, Portfolio, AuditEntry
from ..domain.events import DomainEvent


@runtime_checkable
class ISignalRepository(Protocol):
    async def save_signal(self, signal: Signal) -> Signal: ...
    async def get_signal(self, signal_id: str) -> Signal | None: ...
    async def list_signals(self, limit: int = 50, offset: int = 0, symbol: str | None = None) -> list[Signal]: ...
    async def update_signal_score(self, signal_id: str, score: float) -> None: ...


@runtime_checkable
class IOrderRepository(Protocol):
    async def save_order(self, order: Order) -> Order: ...
    async def get_order(self, order_id: str) -> Order | None: ...
    async def get_order_by_broker_id(self, broker_order_id: str) -> Order | None: ...
    async def update_order(self, order: Order) -> Order: ...
    async def list_orders(self, status: str | None = None, limit: int = 50, offset: int = 0) -> list[Order]: ...


@runtime_checkable
class IPositionRepository(Protocol):
    async def save_position(self, position: Position) -> Position: ...
    async def get_position(self, position_id: str) -> Position | None: ...
    async def get_position_by_symbol(self, symbol: str) -> Position | None: ...
    async def update_position(self, position: Position) -> Position: ...
    async def list_open_positions(self) -> list[Position]: ...
    async def list_all_positions(self, limit: int = 100) -> list[Position]: ...


@runtime_checkable
class IEventStore(Protocol):
    async def append(self, event: DomainEvent) -> None: ...
    async def get_events(self, aggregate_id: str, aggregate_type: str | None = None) -> list[DomainEvent]: ...
    async def get_recent_events(self, limit: int = 100, event_type: str | None = None) -> list[dict[str, Any]]: ...


@runtime_checkable
class IBrokerAdapter(Protocol):
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def submit_order(self, order: Order) -> dict[str, Any]: ...
    async def cancel_order(self, broker_order_id: str) -> bool: ...
    async def get_account(self) -> dict[str, Any]: ...
    async def get_positions(self) -> list[dict[str, Any]]: ...
    async def health_check(self) -> dict[str, Any]: ...


@runtime_checkable
class IMarketDataAdapter(Protocol):
    async def get_quote(self, symbol: str) -> dict[str, Any]: ...
    async def get_ohlcv(self, symbol: str, period: str = "1d", interval: str = "1m") -> list[dict[str, Any]]: ...
    async def get_fundamentals(self, symbol: str) -> dict[str, Any]: ...
    async def get_multiple_quotes(self, symbols: list[str]) -> dict[str, dict[str, Any]]: ...


@runtime_checkable
class IMessageBusPublisher(Protocol):
    async def publish(self, topic: str, event: DomainEvent) -> None: ...
    async def publish_raw(self, topic: str, payload: dict[str, Any]) -> None: ...


@runtime_checkable
class IAIAdapter(Protocol):
    async def analyze(self, prompt: str, context: dict[str, Any]) -> str: ...
    async def structured_analyze(self, prompt: str, context: dict[str, Any]) -> dict[str, Any]: ...
    async def health_check(self) -> dict[str, Any]: ...


@runtime_checkable
class INotificationAdapter(Protocol):
    async def send_trade_alert(self, message: str, data: dict[str, Any]) -> None: ...
    async def send_risk_alert(self, message: str, severity: str = "warning") -> None: ...
    async def send_portfolio_update(self, portfolio_data: dict[str, Any]) -> None: ...


__all__ = [
    "ISignalRepository", "IOrderRepository", "IPositionRepository",
    "IEventStore", "IBrokerAdapter", "IMarketDataAdapter",
    "IMessageBusPublisher", "IAIAdapter", "INotificationAdapter",
]
